language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/Administration
  - secure: fwb1zSPgFcbZEAaTIAc3obpQwgUbeVDB0VLg3Nll0DnNzCu91ztCGSKyLLN0Qe8m0tQTJLkO4a7HmvFexPnmcpgkA5GVj6+RG7s7pyphneVfkvVuwnp0yGryS4+GdywKh6UXaW7a90I/xVSlKs9HYjuUPl0RBW9a1Xm7b+NyKeOYhmt1DhEZxsxrNmLgUYV4aNueRIgGL59P1tXrXZfi96KISnLeJ83tKic8bTdJMDegG+z2VrOpkscbBV9+Jp5O6/FmHBSioZz8+YD9syiXVdV93X+wHsTTwf+XUFGSg4RGGHi6hGW3DIZ7S0MPGa9AQcRsMoTZ7GztEQmMdrmIVaYRVo7In7UhVWqipLXGL6/DUsBIrCgk7/nH9bTG7IkmFG2BFzpZhell/vk4sYA9gBu49rFe/onTq1yulmEjt/W7nYX4SrvleMRiCUdvCx+jtSO5+wXxfkDc+VKlsX/nKOaE/SlA8xD9F9rJGU0Aelz4NQ7hdnJMFKiFDapEh+vaOylur+2hM7krda2g9W/d94VcWSE1MIl6tTO4cU11tUJMGA/wCtpTLJ8AfD2frrJ+Q+8xp0UCjmd8mQ6yozxEASNeS3La7QmZQGDAGYJEMUSSFrGZ116IyThlX20vszdiZkd3yUBBQ3E8EqAv4YDspDMGugh3EpWzh5GQ4cZP0gE=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
- gradle clean --refresh-dependencies
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
